apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raktr.fullname" . }}-frontend
  labels:
    {{- include "raktr.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  {{- include "raktr.frontendConfig" . | trim | default "{}" | nindent 2 }}
