apiVersion: v1
kind: Service
metadata:
  name: {{ include "request-manager.fullname" . }}
  labels:
    {{- include "request-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "request-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
