apiVersion: v1
kind: Secret
metadata:
  name: {{ include "raktr.fullname" . }}-backend
  labels:
    {{- include "raktr.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  {{- include "raktr.backendSecrets" . | trim | default "{}" | nindent 2 }}
