---
misconfigurations:
  - id: AVD-KSV-0014
    paths:
      - charts/outline/charts/postgres/templates/statefulset.yaml
      - charts/outline/charts/redis/templates/statefulset.yaml
    statement: External charts
  - id: AVD-KSV-0110
    paths:
      - charts/outline/templates/cronjob.yaml
      - charts/outline/templates/deployment.yaml
    statement: Actual chart will not be deployed to default namespace
  - id: AVD-KSV-0125
    statement: Used container registries are trusted
