apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost.fullname" . }}
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "mattermost.secrets" . | trim | default "{}" | nindent 2 }}
