apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raktr.fullname" . }}
  labels:
    {{- include "raktr.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- include "raktr.config" . | trim | default "{}" | nindent 2 }}
