apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  {{- include "backstage.config" . | trim | default "{}" | nindent 2 }}
