apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "backstage.secrets" . | trim | default "{}" | nindent 2 }}
