apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "request-manager.fullname" . }}
  labels:
    {{- include "request-manager.labels" . | nindent 4 }}
data:
  {{- $cfg := fromYaml (include "request-manager.config" .) }}
  {{- range $k, $v := $cfg }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
