apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "request-manager.fullname" . }}
  labels:
    {{- include "request-manager.labels" . | nindent 4 }}
data:
  {{- include "request-manager.config" . | trim | default "{}" | nindent 2 }}
