{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "request-manager.fullname" . }}
  labels:
    {{- include "request-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secrets := deepCopy .Values.secrets }}
  {{- if and .Values.postgres.enabled (not (hasKey .Values.secrets "DATABASE_PASSWORD")) }}
  {{- $_ := set $secrets "DATABASE_PASSWORD" .Values.postgres.auth.password }}
  {{- end }}
  {{- range $k, $v := $secrets }}
  {{- if and (not (kindIs "invalid" $v)) (ne ($v | toString) "") }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
