apiVersion: v1
kind: Secret
metadata:
  name: {{ include "request-manager.fullname" . }}
  labels:
    {{- include "request-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "request-manager.secrets" . | trim | default "{}" | nindent 2 }}
