apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  {{- include "outline.config" . | trim | default "{}" | nindent 2 }}
