apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  {{- include "outline.env" (dict "root" . "values" .Values.outline) | indent 2 }}
  {{- include "outline.envVars" . | indent 2 }}
