apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "outline.secrets" . | trim | nindent 2 }}
