---
name: Lint and Test Charts

on:
  push:
  pull_request:

jobs:
  lint-test:
    name: Lint and Test Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup Chart Linting
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: 3.11.0
          yamllint_version: 1.35.1

      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct --config ./.github/configs/ct.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "changed_charts=$charts" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --debug --config ./.github/configs/ct.yaml --lint-conf ./.github/configs/lintconf.yaml

      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          ./scripts/helm-docs.sh
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated!\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ./.github/configs/ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
